services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    environment:
      ConnectionStrings__DefaultConnection: "Server=database;Database=BrasilTerrenos;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;"
      ASPNETCORE_ENVIRONMENT: "${APP_ENV}"
      ASPNETCORE_URLS: "http://+:8080"

    depends_on:
      database:
        condition: service_started

  database:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: brasil-terrenos-database

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${DB_PASSWORD}"

    ports:
      - "1433:1433"

    volumes:
      - sqlserver_data:/var/opt/mssql

    restart: unless-stopped

volumes:
  sqlserver_data: